### ISSUE TITLE
There is no way to access `push` through SFMCSdk

### ISSUE THREAD

**Issue by lupugabriel** [salesforce-marketingcloud/sfmc-sdk-ios#1]
SFMCSdk does not have any member push.
This is not accessible. We need this for initialization and other calls like getting all messages.

**Example 1:**
Trying to get messages
SFMCSdk.push.getAllMessages()
Error:
Type 'SFMCSdk' has no member 'push'

**Example 2:**

// With manual check on the module initialization success
let configuration = PushConfigBuilder(appId: PUSH_APP_ID)
     .setAccessToken(PUSH_ACCESS_TOKEN)
     .setMarketingCloudServerUrl(URL(string: PUSH_TSE)!)
     .build()

SFMCSdk.initializeSdk(ConfigBuilder().setPush(config: configuration).build())

if SFMCSdk.push.getStatus() == .operational {
     //function logic
}

Error:
Type 'SFMCSdk' has no member 'push'

I can confirm that integration seems good. The initializations works fine the completion handler initialization.
Can you please fix this? There is no way to update if this is not fix.
![Screenshot 2021-09-28 at 10 28 18](https://user-images.githubusercontent.com/3657507/135061536-b72b8639-af75-46c9-b18d-ea258237a47f.jpg)

**Comment by billmote** [comment]
There was a last minute change by product to call this `mp`.  Please substitute `mp` for `push` in the spots you've referenced.
